#index:
#    path: /
#    controller: App\Controller\DefaultController::index


product:
            path: /product
            controller: App\Controller\ProductController::product

product_add:
            path: /products/add
            controller: App\Controller\ProductAddController::product_add

product_edit:
            path: /products/edit/{id}
            controller: App\Controller\ProductEditController::product_edit  

product_delete:
            path: /products/delete/{id}
            controller: App\Controller\ProductEditController::product_delete

person:
            path: /person
            controller: App\Controller\PersonController::person

person_add:
            path: /persons/add
            controller: App\Controller\PersonAddController::person_add

person_edit:
            path: /person/edit/{id}
            controller: App\Controller\PersonEditController::person_edit  

person_delete:
            path: /person/delete/{id}
            controller: App\Controller\PersonEditController::person_delete  


